import { IPatient, HeadCell } from './AcceptanceDataInterfaces';

export const Status = [
  { title: '診療待', color: 'DEEPSKYBLUE', textColor: 'black' },
  { title: '送信待', color: 'VIOLET', textColor: 'black' },
  { title: '送信済', color: 'LIME', textColor: 'black' },
  { title: '取り消し', color: 'RED', textColor: 'white' },
];

function createData(
  Acceptance_ID: string,
  Patient_ID: string,
  Status: string,
  WholeName: string,
  WholeName_inKana: string,
  BirthDate: string,
  Sex: string,
  Acceptance_Time: string,
  InsuranceProvider_WholeName: string,
  Department_WholeName: string,
  Physician_WholeName: string,
  Previouse_Acceptance_Date: string,
  Patient_Memo: string,
  Acceptance_Memo: string
): IPatient {
  return {
    Acceptance_ID,
    Patient_ID,
    Status,
    WholeName,
    WholeName_inKana,
    BirthDate,
    Sex,
    Acceptance_Time,
    InsuranceProvider_WholeName,
    Department_WholeName,
    Physician_WholeName,
    Previouse_Acceptance_Date,
    Patient_Memo,
    Acceptance_Memo,
  };
}

export const headCells: HeadCell[] = [
  { id: 'Acceptance_ID', disablePadding: true, label: '番号' },
  { id: 'Acceptance_Time', disablePadding: true, label: '時間' },
  { id: 'Status', disablePadding: true, label: 'ステータス' },
  { id: 'Patient_ID', disablePadding: true, label: '患者番号' },
  { id: 'WholeName_inKana', disablePadding: true, label: 'フリガナ' },
  { id: 'WholeName', disablePadding: true, label: '名前' },
  { id: 'BirthDate', disablePadding: true, label: '生年月日' },
  { id: 'Sex', disablePadding: true, label: '性別' },
  { id: 'InsuranceProvider_WholeName', disablePadding: true, label: '保険' },
  { id: 'Department_WholeName', disablePadding: true, label: '診療科' },
  { id: 'Physician_WholeName', disablePadding: true, label: '医師' },
  {
    id: 'Previouse_Acceptance_Date',
    disablePadding: true,
    label: '前回受付日',
  },
  { id: 'Patient_Memo', disablePadding: true, label: '患者メモ' },
  { id: 'Acceptance_Memo', disablePadding: true, label: '受付メモ' },
];

export const AcceptanceData = [
  createData(
    '001',
    '305',
    '0',
    '67',
    '4.3',
    'Cupcake',
    '305',
    '67',
    '4.3',
    'Cupcake',
    '305',
    '3.7',
    '67',
    '4.3'
  ),
  createData(
    '002',
    '452',
    '0',
    '51',
    '4.9',
    'Donut',
    '452',
    '51',
    '4.9',
    'Donut',
    '452',
    '25.0',
    '51',
    '4.9'
  ),
  createData(
    '003',
    '262',
    '1',
    '24',
    '6.0',
    'Eclair',
    '16.0',
    '24',
    '6.0',
    'Eclair',
    '262',
    '16.0',
    '24',
    '6.0'
  ),
  createData(
    '004',
    '159',
    '0',
    '24',
    '4.0',
    'Frozen yoghurt',
    '159',
    '24',
    '4.0',
    'Frozen yoghurt',
    '159',
    '6.0',
    '24',
    '4.0'
  ),
  createData(
    '005',
    '356',
    '2',
    '49',
    '3.9',
    'Gingerbread',
    '356',
    '49',
    '3.9',
    'Gingerbread',
    '356',
    '16.0',
    '49',
    '3.9'
  ),
  createData(
    '006',
    '408',
    '0',
    '87',
    '6.5',
    'Honeycomb',
    '408',
    '87',
    '6.5',
    'Honeycomb',
    '408',
    '3.2',
    '87',
    '6.5'
  ),
  createData(
    '007',
    '237',
    '0',
    '37',
    '4.3',
    'Ice cream sandwich',
    '237',
    '37',
    '4.3',
    'Ice cream sandwich',
    '237',
    '9.0',
    '37',
    '4.3'
  ),
  createData(
    '008',
    '375',
    '2',
    '94',
    '0.0',
    'Jelly Bean',
    '375',
    '94',
    '0.0',
    'Jelly Bean',
    '375',
    '0.0',
    '94',
    '0.0'
  ),
  createData(
    '009',
    '518',
    '2',
    '65',
    '7.0',
    'KitKat',
    '518',
    '65',
    '7.0',
    'KitKat',
    '518',
    '26.0',
    '65',
    '7.0'
  ),
  createData(
    '010',
    '392',
    '2',
    '98',
    '0.0',
    'Lollipop',
    '392',
    '98',
    '0.0',
    'Lollipop',
    '392',
    '0.2',
    '98',
    '0.0'
  ),
  createData(
    '011',
    '318',
    '0',
    '81',
    '2.0',
    'Marshmallow',
    '318',
    '81',
    '2.0',
    'Marshmallow',
    '318',
    '0',
    '81',
    '2.0'
  ),
  createData(
    '012',
    '360',
    '1',
    '9',
    '37.0',
    'Nougat',
    '360',
    '9',
    '37.0',
    'Nougat',
    '360',
    '19.0',
    '9',
    '37.0'
  ),
  createData(
    '013',
    '437',
    '0',
    '63',
    '4.0',
    'Oreo',
    '437',
    '63',
    '4.0',
    'Oreo',
    '437',
    '18.0',
    '63',
    '4.0'
  ),
];

export default AcceptanceData;
